### ISSUE TITLE
Game broke at <html>

### ISSUE THREAD

**Issue by paurakhsharma** [Contrevien/word-beater#1]
Game stopped working at `<html>`

![image](https://user-images.githubusercontent.com/20378877/62845886-94206c00-bceb-11e9-8e6f-e29ee9c48740.png)

**Comment by aleksa26** [comment]
> Game stopped working at `<html>`
> 
> ![image](https://user-images.githubusercontent.com/20378877/62845886-94206c00-bceb-11e9-8e6f-e29ee9c48740.png)

Hi, I solved it in this pull request #2 . There was comparison between `&lt;` and < (and also `&gt;` and >) which is not equal. So i made a method which decodes html character entities and returns real html. Could you check it please?

**Comment by Contrevien** [comment]
Really sorry for delayed reply. Thank you for noticing and raising the issue. Similarly, thank you @aleksa26 for solving the same in #2
